### PR TITLE
Added HelloWorld - F#

### PR DESCRIPTION
**Pull request by rishitsaiya**

### CODE REVIEW

**Review by abhiisshheekk — APPROVED** [review]
I see you're not afraid of Injection! Ahaa!

**Review by Shiru99 — APPROVED** [review]
Because sometimes, even if you know how something’s going to end, that doesn’t mean you can’t enjoy the ride. :1st_place_medal:

**Review by harshraj22 — COMMENTED** [review]
# ek dum se waqt badal diya, jazbaat badal diye, zindagi badal di ! Ooooo bhai, maro ! mujhe maro !

**Review by Manjeetkapil — COMMENTED** [review]
Aboveground

**Review by Manjeetkapil — APPROVED** [review]

**Comment by iam41** [comment]
i always wonder how this was done...
your comment made it several times easier.

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
