### PR TITLE
C# exe file for Hello World

### PR DESCRIPTION
**Pull request by Shiru99**

### CODE REVIEW

**Review by abhiisshheekk — APPROVED** [review]
LGTM!

**Review by rishitsaiya — APPROVED** [review]
Yeh main kya kar rha hu! :+1:

**Review by harshraj22 — APPROVED** [review]
### I can see Investers fighting for this WhiteHat jounior

**Comment by Shiru99** [comment]
If you’re looking for a word that means caring about someone beyond all rationality and wanting them to have everything they want, no matter how much it destroys you, it’s ‘love. :1st_place_medal:

**Review by Manjeetkapil — APPROVED** [review]
Bhai mery memory full ho gyi install karte karte

**Comment by Shiru99** [comment]
> Bhai mery memory full ho gyi install karte karte

agale saal uninstall kaise karna he daalenge :+1:

**Pull request merged**
