### PR TITLE
Added Assembly x86 Code

### PR DESCRIPTION
**Pull request by rishitsaiya**

### CODE REVIEW

**Review by Shiru99 — APPROVED** [review]
Interesting Topic
great idea

**Review by harshraj22 — APPROVED** [review]
### Mera assignment bhi kar de :rofl:

**Comment by rishitsaiya** [comment]
> ### Mera assignment bhi kar de rofl

Chintu wants to know your location :pushpin: :rofl:

**Review by abhiisshheekk — APPROVED** [review]
I knew I would find you here chintu. Go to you home and play with you figurines.

**Review by Manjeetkapil — APPROVED** [review]
Assembly samjh nhi aata

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
