### PR TITLE
Occurences

### PR DESCRIPTION
**Pull request by harshraj22**

### CODE REVIEW

**Review by abhiisshheekk — APPROVED** [review]
Good job! Now you are free

**Review by Shiru99 — APPROVED** [review]
very useful for beginners! 
Informative !!
Life Saviour !!!

**Review by rishitsaiya — APPROVED** [review]
Good resource for beginners! :100:

**Review by Manjeetkapil — APPROVED** [review]
-50 kato python ke

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
