### PR TITLE
C# installation Shell Script

### PR DESCRIPTION
**Pull request by Shiru99**

### CODE REVIEW

**Review by rishitsaiya — APPROVED** [review]
I never knew this :+1:

**Review by abhiisshheekk — APPROVED** [review]
I just wanna say that I am a huge fan!

**Review by harshraj22 — APPROVED** [review]
This is the most important contribution humans have ever made ! You have made our country proud !

**Comment by Rupesh282** [comment]
OMG

**Comment by harshraj22** [comment]
> OMG

@Rupesh282 welcome to the battlefield ! the war has begun ! :sunglasses:

**Review by Manjeetkapil — APPROVED** [review]
I need this

**Comment by Shiru99** [comment]
It’s only once you’ve stopped that you realize how hard it is to start again.

**Comment by Shiru99** [comment]
> OMG

Because sometimes, even if you know how something’s going to end, that doesn’t mean you can’t enjoy the ride. :1st_place_medal:

**Pull request merged**
