### PR TITLE
added hello world in minecraft

### PR DESCRIPTION
**Pull request by abhiisshheekk**

### CODE REVIEW

**Review by harshraj22 — APPROVED** [review]
congratulations ! for this great efforts of yours, you are selected for the intra space-time-galactic mission ! You will be sent to parallel universe, travelling through time, to meet Naruto ! send him hello from my side . :rofl:

**Review by rishitsaiya — APPROVED** [review]
Thanks for this! Learnt something new! :confetti_ball:

**Review by Shiru99 — APPROVED** [review]
I know it’s a mistake, but there are certain things in life where you know it’s a mistake, but you don’t really know it’s a mistake, because the only way to really know it’s a mistake is to make the mistake, and look back and say, ‘Yep, that was a mistake.’ So, really, the bigger mistake would be to not make the mistake because then you’d go your whole life not really knowing if something is a mistake or not. :1st_place_medal:

**Comment by abhiisshheekk** [comment]
Thank you Galactic President Superstar McAwesomeville 😄

**Review by Manjeetkapil — APPROVED** [review]
Jow u do tjis

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
