### PR TITLE
added hello world program in fish

### PR DESCRIPTION
**Pull request by abhiisshheekk**

### CODE REVIEW

**Review by harshraj22 — APPROVED** [review]
Great ! This was most required ! Now we can talk to fishes ! We will remake the movie `finding nemo` in their native language ! :dark_sunglasses:

**Review by rishitsaiya — APPROVED** [review]
Yes! Aquaman will be the new ruler of the world and he will need this language! Nicely done :confetti_ball:

**Review by Shiru99 — APPROVED** [review]
Whatever you do in this life, it’s not legendary unless your friends are there to see it. :1st_place_medal:

**Review by Manjeetkapil — APPROVED** [review]
Fish queen of water

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
