### PR TITLE
Added HelloWorld - HTML

### PR DESCRIPTION
**Pull request by rishitsaiya**

### CODE REVIEW

**Review by abhiisshheekk — APPROVED** [review]
Your future self is proud of you!

**Review by harshraj22 — APPROVED** [review]
150 rupiya dega !

**Review by Shiru99 — APPROVED** [review]
If you’re looking for a word that means caring about someone beyond all rationality and wanting them to have everything they want, no matter how much it destroys you, it’s ‘love.' :1st_place_medal:

**Review by Manjeetkapil — APPROVED** [review]
Pr ab sikh jaunga crypto

**Comment by iam41** [comment]
i literally dont have words to describe my feelings.

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
