### PR TITLE
edit

### PR DESCRIPTION
**Pull request by iam41**
added uninstalling commands

### CODE REVIEW

**Review by Jerry1919 — APPROVED** [review]
Hmm 

great Job

**Review by abhiisshheekk — APPROVED** [review]
Yes yes yes! This is what was missing from these readme files!

## Tum bahot mast kam karta hai!

**Review by Jerry1919 — APPROVED** [review]
Nice well done !

**Comment by iam41** [comment]
> Hmm
> 
> great Job

> Hmm
> 
> great Job

thanks...
now the world may not face catastrophe.

**Comment by iam41** [comment]
> Yes yes yes! This is what was missing from these readme files!
> ## Tum bahot mast kam karta hai!

thankssssssssssssssssssssss$$$$$$$$$$$$

**Review by Shiru99 — APPROVED** [review]
“You can’t design your life like a building. It doesn’t work that way. You just have to live it, and it will design itself. Listen to what the world is telling you to do and take the leap.” — Lily Aldrin (“The Leap”)

**Comment by Shiru99** [comment]
> > Yes yes yes! This is what was missing from these readme files!
> > ## Tum bahot mast kam karta hai!
> 
> thankssssssssssssssssssssss$$$$$$$$$$$$

but i guess ye tera overall 1 hi PR tha tuze aur 3PR chahiye

**Comment by iam41** [comment]
> “You can’t design your life like a building. It doesn’t work that way. You just have to live it, and it will design itself. Listen to what the world is telling you to do and take the leap.” — Lily Aldrin (“The Leap”)
you want me to design a building for you??🤔🤔🤔

**Comment by abhiisshheekk** [comment]
> > > Yes yes yes! This is what was missing from these readme files!
> > > ## Tum bahot mast kam karta hai!
> > 
> > 
> > thankssssssssssssssssssssss$$$$$$$$$$$$
> 
> but i guess ye tera overall 1 hi PR tha tuze aur 3PR chahiye

**Review by Manjeetkapil — APPROVED** [review]
Yhi toh chahite tha

**Review by rishitsaiya — APPROVED** [review]
Dart/ReadMe.md mein changes fix karo. PR merge conflict dera hai woh file ke liye!

**Comment by abhiisshheekk** [comment]
Its resolved now!

**Review by abhiisshheekk — APPROVED** [review]
Once Again approved!

**Review by harshraj22 — APPROVED** [review]
### chaangleee :smiley_cat:

**Comment by abhiisshheekk** [comment]
> ### chaangleee 😺

### itthe kutthe 😸

**Pull request merged**
