### PR TITLE
Kotlin Installation Shell script

### PR DESCRIPTION
**Pull request by Shiru99**
Kotlin Installation Shell script

### CODE REVIEW

**Review by rishitsaiya — APPROVED** [review]
This should be on your Blog as well! Nice work! :confetti_ball:

**Review by harshraj22 — APPROVED** [review]
Great work ! We will install this on github's servers

**Review by abhiisshheekk — APPROVED** [review]
@harshraj22 Absolutively

**Review by Manjeetkapil — APPROVED** [review]
Noice work

**Comment by Shiru99** [comment]
I know it’s a mistake, but there are certain things in life where you know it’s a mistake, but you don’t really know it’s a mistake, because the only way to really know it’s a mistake is to make the mistake, and look back and say, ‘Yep, that was a mistake.’ So, really, the bigger mistake would be to not make the mistake because then you’d go your whole life not really knowing if something is a mistake or not :+1:

**Pull request merged**
