### PR TITLE
Kotlin Installation.md

### PR DESCRIPTION
**Pull request by Shiru99**

### CODE REVIEW

**Review by abhiisshheekk — APPROVED** [review]
This isn't what we deserved but needed. Keep up the good work!

**Review by harshraj22 — APPROVED** [review]
I see, you are a man of culture !

**Comment by Shiru99** [comment]
I know it’s a mistake, but there are certain things in life where you know it’s a mistake, but you don’t really know it’s a mistake, because the only way to really know it’s a mistake is to make the mistake, and look back and say, ‘Yep, that was a mistake.’ So, really, the bigger mistake would be to not make the mistake because then you’d go your whole life not really knowing if something is a mistake or not. :1st_place_medal:

**Review by rishitsaiya — APPROVED** [review]
Just by reviewing, I have learnt Kotlin :smile_cat:

**Review by Manjeetkapil — APPROVED** [review]
4 th time installation in progress

**Pull request merged**
