### PR TITLE
Quick sort

### PR DESCRIPTION
**Pull request by harshraj22**

### CODE REVIEW

**Review by Shiru99 — APPROVED** [review]
well, great to learn such sorting techniques

**Review by rishitsaiya — APPROVED** [review]
INKO KYA HI PATA CHALEGA :rofl:

**Review by abhiisshheekk — APPROVED** [review]
Ohh its so quick, its faster than chuck (you know from angry birds)

**Review by Manjeetkapil — APPROVED** [review]
Quicker than quikr

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
