### PR TITLE
C# Installation

### PR DESCRIPTION
**Pull request by Shiru99**

### CODE REVIEW

**Review by abhiisshheekk — APPROVED** [review]
Only those who are ready to be killed have right to kill - Lelouch V Britannia

**Review by harshraj22 — APPROVED** [review]
### Kya gunda banega re tu ?

**Comment by Shiru99** [comment]
It’s not about proof; it’s about faith. Faith is what gives life shape and meaning. :100: :+1:

**Review by rishitsaiya — APPROVED** [review]
I can reverse this hash right?

**Review by Manjeetkapil — APPROVED** [review]
Installed this but don't know where to use

**Pull request merged**
