### PR TITLE
added hello world program in matlab

### PR DESCRIPTION
**Pull request by abhiisshheekk**

### CODE REVIEW

**Review by harshraj22 — APPROVED** [review]
`Kya matlab` ?

**Review by Shiru99 — APPROVED** [review]
very useful for beginners! :+1: 
Informative !! :100: 

really great job :1st_place_medal:

**Review by rishitsaiya — APPROVED** [review]
Kya <b>Matlab</b> HelloWorld? :100:

**Review by Manjeetkapil — APPROVED** [review]
Cool post nice idea i am actively looking for this post from very long time

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
