### PR TITLE
Added Hello World - Karel

### PR DESCRIPTION
**Pull request by rishitsaiya**

### CODE REVIEW

**Review by abhiisshheekk — APPROVED** [review]
Amazing! 💯

**Review by harshraj22 — APPROVED** [review]
This inception is far better than the Hollywood ! Doing great ! Your place for short film making secy for next cult meet is fixed ! :100:

**Review by Shiru99 — APPROVED** [review]
We need to accept that we won’t always make the right decisions, that we’ll screw up royally sometimes – understanding that failure is not the opposite of success, it’s part of success.

**Review by Manjeetkapil — APPROVED** [review]
Cool idea

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
