### PR TITLE
edit

### PR DESCRIPTION
**Pull request by iam41**
edited the kotlin readme.

### CODE REVIEW

**Review by abhiisshheekk — APPROVED** [review]
“This world is rotten, and those who are making it rot deserve to die. Someone has to do it, so why not me?” - Light Yagami 🎖️

**Review by Manjeetkapil — APPROVED** [review]
Party toh banti h isi baat pe

**Review by Shiru99 — APPROVED** [review]
Because maybe it's dumb to look for signs from the universe! Maybe the universe has better things. I mean, dear God, I hope it does. You know how many signs I've gotten, that I should or shouldn't be with someone? And where has it gotten me? Maybe there aren't any signs. Maybe... maybe a locket's just a locket, and a chair's just a chair. Maybe we don't have to give meaning to every little thing. And maybe we don't... Maybe we don't need the universe to tell us what we really want. Maybe we already know that. Deep down.

**Comment by Shiru99** [comment]
> “This world is rotten, and those who are making it rot deserve to die. Someone has to do it, so why not me?” - Light Yagami

let's start with KaRan LOL

**Review by rishitsaiya — APPROVED** [review]
CSE roxx

**Pull request merged**
