### PR TITLE
Added HelloWorld - XML

### PR DESCRIPTION
**Pull request by rishitsaiya**

### CODE REVIEW

**Review by harshraj22 — APPROVED** [review]
Wow ! Now we can play disco while typing ! This is the greatest help to mankind ! You are doing a great job ! Your name will be remembered as long as there is life on earth ! :sunglasses:

**Review by Shiru99 — APPROVED** [review]
Life Saviour keyboard in Disco 
well explained and very informative

**Review by abhiisshheekk — APPROVED** [review]
So you're the disco dancer, I've heard many legends about you like you can dance on dance floor, how do you do that?

**Comment by rishitsaiya** [comment]
> So you're the disco dancer, I've heard many legends about you like you can dance on dance floor, how do you do that?

Learnt from the master himself: @harshraj22 :dancers:

**Review by Manjeetkapil — APPROVED** [review]
Dil me mere h dard e disco

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
