### PR TITLE
Go Installation Shell Script

### PR DESCRIPTION
**Pull request by Shiru99**
Go Installation Shell Script

### CODE REVIEW

**Review by abhiisshheekk — APPROVED** [review]
You will be avenged!

**Review by harshraj22 — APPROVED** [review]
Wow ! After reading this script, my laptop is ready to go. Great script !

**Comment by Shiru99** [comment]
I know it’s a mistake, but there are certain things in life where you know it’s a mistake, but you don’t really know it’s a mistake, because the only way to really know it’s a mistake is to make the mistake, and look back and say, ‘Yep, that was a mistake.’ So, really, the bigger mistake would be to not make the mistake because then you’d go your whole life not really knowing if something is a mistake or not. :1st_place_medal:

**Review by Manjeetkapil — APPROVED** [review]
Thanks william

**Review by rishitsaiya — APPROVED** [review]
Is this script "ShellFish"? :rofl:

**Pull request merged**
