### PR TITLE
Hello world in 2 times in python

### PR DESCRIPTION
**Pull request by Pasindu-Vishmika**
Hello world in 2 times in python

### CODE REVIEW

**Review by rishitsaiya — CHANGES_REQUESTED** [review]
Please change the files location to Python directory.

**Comment by Pasindu-Vishmika** [comment]
can you close this and i'll create new full request

**Comment by rishitsaiya** [comment]
You can change in this same PR itself. Can you try it?

**Review by rishitsaiya — CHANGES_REQUESTED** [review]
Changes are still pending. Push them in Python directory if u can!

**Comment by Pasindu-Vishmika** [comment]
I am sorry,

I am new to GitHub and I tried but I couldn't do that

**Comment by rishitsaiya** [comment]
Ok, no problem. I'll do that.
But you can checkout this PR locally and then commit the changes on this same PR.

**Comment by Pasindu-Vishmika** [comment]
Thank you for accepting my pull request.I'll learn that

@rishitsaiya  Please add the label as **hacktoberfest-accepted**

**Comment by rishitsaiya** [comment]
Just check your portal once, if this PR got added there? This repo is Hacktoberfest labeled, so PR need not be labeled separately

**Comment by Pasindu-Vishmika** [comment]
Thank you so much @rishitsaiya  :) <3

**Pull request merged**
