### PR TITLE
Added HelloWorld - Latex

### PR DESCRIPTION
**Pull request by rishitsaiya**

### CODE REVIEW

**Review by Shiru99 — APPROVED** [review]
very useful for beginners! 
Informative !!

**Review by harshraj22 — APPROVED** [review]
Wow ! Awesome ! You finally did it ! 
## wow adi, you are so smart !

**Review by abhiisshheekk — APPROVED** [review]
"Feel pain, think about pain, accept pain, know pain!"
Literally no one:

**Comment by rishitsaiya** [comment]
> "Feel pain, think about pain, accept pain, know pain!"
> Literally no one:

John Cena wants to know your location :roll_eyes: :rofl:

**Comment by Shiru99** [comment]
I know it’s a mistake, but there are certain things in life where you know it’s a mistake, but you don’t really know it’s a mistake, because the only way to really know it’s a mistake is to make the mistake, and look back and say, ‘Yep, that was a mistake.’ So, really, the bigger mistake would be to not make the mistake because then you’d go your whole life not really knowing if something is a mistake or not. :1st_place_medal:

**Review by Manjeetkapil — APPROVED** [review]
Cool post

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
