### PR TITLE
Heap sort

### PR DESCRIPTION
**Pull request by harshraj22**
first commit

### CODE REVIEW

**Review by Shiru99 — APPROVED** [review]
Great sorting tool

**Review by abhiisshheekk — APPROVED** [review]
Hip hop!

**Review by rishitsaiya — APPROVED** [review]
Nicely Done!

**Review by Manjeetkapil — APPROVED** [review]
Aaj sab sort ho jayega tera aur uska tension naa le

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
