### PR TITLE
Manjeet3

### PR DESCRIPTION
**Pull request by Manjeetkapil**

### CODE REVIEW

**Comment by Manjeetkapil** [comment]
thanks @abhiisshheekk

**Review by harshraj22 — APPROVED** [review]
Great code ! This would bring great changes in technical wold ! Mankind will remember you for this help till the eternity !

**Review by rishitsaiya — APPROVED** [review]
Ah! I see! You're a man of culture!

**Comment by rishitsaiya** [comment]
> I see so you are the comedy king. smile

Komedy is his passion! :rofl:

**Review by Shiru99 — APPROVED** [review]
It’s not about proof; it’s about faith. Faith is what gives life shape and meaning

**Comment by iam41** [comment]
why do your edits always make it so fluent?

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
