### PR TITLE
Added HelloWorld - Cobol

### PR DESCRIPTION
**Pull request by rishitsaiya**

### CODE REVIEW

**Review by harshraj22 — APPROVED** [review]
Great work ! Create your own android ! Will be waiting for updates ! :telephone_receiver:

**Review by abhiisshheekk — APPROVED** [review]
Reverse Approval!

**Review by Shiru99 — APPROVED** [review]
If you’re not scared, you’re not taking a chance, and if you’re not taking a chance, then what the hell are you doing? :100:

**Review by Manjeetkapil — APPROVED** [review]

**Comment by iam41** [comment]
mu goodness

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
