### PR TITLE
Go Installation.md

### PR DESCRIPTION
**Pull request by Shiru99**
Go Installation.md

### CODE REVIEW

**Review by abhiisshheekk — APPROVED** [review]
You won't regret this. You'll be proud!

**Review by harshraj22 — APPROVED** [review]
Great contribution ! Well done ! You invented your own language to write the installation process !

**Comment by Shiru99** [comment]
If you’re not scared, you’re not taking a chance, and if you’re not taking a chance, then what the hell are you doing? :100:

**Review by rishitsaiya — APPROVED** [review]
Nice!

**Review by Manjeetkapil — APPROVED** [review]
Installed 3 rd time kotlin

**Pull request merged**
