### PR TITLE
Binary search

### PR DESCRIPTION
**Pull request by harshraj22**
first commit

### CODE REVIEW

**Review by Shiru99 — APPROVED** [review]
Very Informative topic

**Review by rishitsaiya — APPROVED** [review]
I learnt something new today! :muscle:

**Review by Manjeetkapil — APPROVED** [review]

**Review by abhiisshheekk — APPROVED** [review]
01001110 01101001 01100011 01100101 00100001

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
