### PR TITLE
added lcotodo

### PR DESCRIPTION
**Pull request by Manjeetkapil**
FOR ALL OF YOU

### CODE REVIEW

**Review by rishitsaiya — APPROVED** [review]

**Comment by rishitsaiya** [comment]
This is gonna be my BTP. Nobody will touch it :rofl:

**Review by abhiisshheekk — APPROVED** [review]
I needed this. Thanks!

**Review by Shiru99 — APPROVED** [review]
Every night can’t be legendary. If all nights are legendary, no nights are legendary. :100:

**Comment by abhiisshheekk** [comment]
> Every night can’t be legendary. If all nights are legendary, no nights are legendary. 💯

By Ted Mosby

**Review by harshraj22 — APPROVED** [review]
### College nahi khulega

**Comment by iam41** [comment]
oh my god...

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
