### PR TITLE
Insertion sort

### PR DESCRIPTION
**Pull request by harshraj22**
first commit

### CODE REVIEW

**Review by Shiru99 — APPROVED** [review]
very informative algorithm for beginners

**Review by abhiisshheekk — APPROVED** [review]
Insert disc 2

**Review by rishitsaiya — APPROVED** [review]
I expect this code to sort when I insert it :rofl:

**Review by Manjeetkapil — APPROVED** [review]
Kiran se sab  sorted h naa

**Review by iam41 — COMMENTED** [review]
nicely done.

**Comment by harshraj22** [comment]
> Kiran se sab sorted h naa

Kiran is :heart:

**Pull request merged**
