### PR TITLE
Dp

### PR DESCRIPTION
**Pull request by harshraj22**

### CODE REVIEW

**Review by Shiru99 — COMMENTED** [review]
very useful for beginners! 
Informative !!

**Review by abhiisshheekk — APPROVED** [review]
Nice Dp. Its by far the best dp anyone could have.

**Review by rishitsaiya — APPROVED** [review]
I used this code to put my whatsapp profile pic

**Comment by Shiru99** [comment]
Every night can’t be legendary. If all nights are legendary, no nights are legendary.

**Review by Manjeetkapil — APPROVED** [review]
Pls add c++ content

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
