### PR TITLE
Added Hello World - C Language

### PR DESCRIPTION
**Pull request by rishitsaiya**

### CODE REVIEW

**Review by harshraj22 — APPROVED** [review]
I see you are a man of culture ! Great job !

**Review by Shiru99 — APPROVED** [review]
Real 'Hello World' starts with C !!!

**Review by abhiisshheekk — APPROVED** [review]
I can C now Lol

**Review by Manjeetkapil — APPROVED** [review]
World saver file

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
