### PR TITLE
Dart Installation.md

### PR DESCRIPTION
**Pull request by Shiru99**

### CODE REVIEW

**Review by abhiisshheekk — APPROVED** [review]
"Justice comes from vengeance, but that justice only breeds more vengeance."

Your code will save humanity from its inevitable doom!

**Comment by Shiru99** [comment]
> "Justice comes from vengeance, but that justice only breeds more vengeance."
> 
> Your code will save humanity from its inevitable doom!

Every night can’t be legendary. If all nights are legendary, no nights are legendary. :1st_place_medal:

**Review by harshraj22 — APPROVED** [review]
##### Too much of hard work ! As prize, you will be the last to called, if the college ever opens. !!

**Comment by Shiru99** [comment]
Never underestimate the power of destiny. Because when you least expect it, the littlest thing can cause a ripple effect that changes your life. :1st_place_medal: :100: :+1:

**Review by rishitsaiya — APPROVED** [review]
With great power, comes great responsibility! :+1:

**Review by Manjeetkapil — APPROVED** [review]
Great post

**Pull request merged**
