### PR TITLE
edit Go

### PR DESCRIPTION
**Pull request by iam41**
edited readme of go.

### CODE REVIEW

**Review by abhiisshheekk — APPROVED** [review]
“If Kira gets caught, he is evil. If Kira rules the world, he is justice.” - Light Yagami 💯

**Review by Manjeetkapil — APPROVED** [review]
Why u edit everything bro

**Review by Shiru99 — APPROVED** [review]
If you keep giving up on people so quickly, you're going to miss out on something great.

**Review by rishitsaiya — APPROVED** [review]
Yehi toh hai asli Telont 🚀

**Review by harshraj22 — APPROVED** [review]
## ain't ra :confused:

**Pull request merged**
