### PR TITLE
Dart Installation Shell script

### PR DESCRIPTION
**Pull request by Shiru99**

### CODE REVIEW

**Review by harshraj22 — APPROVED** [review]
Great code ! Detailed steps ! Would you like to be CEO of Google ? :100:

**Comment by rishitsaiya** [comment]
> Great code ! Detailed steps ! Would you like to be CEO of Google ? 100

Please give him job in your company :rofl:

**Review by rishitsaiya — APPROVED** [review]
LGTM! :rocket:

**Review by abhiisshheekk — APPROVED** [review]
Sometimes you must hurt in order to know, fall in order to grow, lose in order to gain because life's greatest lessons are learned through pain. - Nagato (aka Pain)

**Comment by Shiru99** [comment]
You can’t design your life like a building. It doesn’t work that way. You just have to live it, and it will design itself. Listen to what the world is telling you to do and take the leap. :1st_place_medal:

**Review by Manjeetkapil — APPROVED** [review]
It's getting full now stack has no place to receive this

**Pull request merged**
