### PR TITLE
Manjeet

### PR DESCRIPTION
**Pull request by Manjeetkapil**
hello

### CODE REVIEW

**Review by harshraj22 — APPROVED** [review]
Great work ! This pull request will save the humanity for ages ! You will be remembered till the d-day ! :100:

**Review by rishitsaiya — APPROVED** [review]
Apocalype bachayega yeh code! :rocket:

**Review by Shiru99 — APPROVED** [review]
very useful for beginners! :+1: 
Informative !! :100: 

really great job :1st_place_medal:

**Review by abhiisshheekk — APPROVED** [review]
"Religion, ideology, resources, land, spite, love or just because. No matter how pathetic the reason, it's enough to start a war."
You'll save everyone from this pain called life.

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
