### PR TITLE
added hello world in javaScript

### PR DESCRIPTION
**Pull request by abhiisshheekk**

### CODE REVIEW

**Review by harshraj22 — APPROVED** [review]
I see, you have great command over this cancerous language ! Definitely you will swap places with Sundar !

**Review by Shiru99 — APPROVED** [review]
Every night can’t be legendary. If all nights are legendary, no nights are legendary. :+1:

**Review by rishitsaiya — APPROVED** [review]
WOW! Just wow

**Review by Manjeetkapil — APPROVED** [review]
This made my day

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
