### PR TITLE
added myapp

### PR DESCRIPTION
**Pull request by Manjeetkapil**

### CODE REVIEW

**Review by abhiisshheekk — APPROVED** [review]
Its your app. I get it but can I use it? pretty please!

**Review by Shiru99 — APPROVED** [review]
Whatever you do in this life, it’s not legendary unless your friends are there to see it. :1st_place_medal:

**Review by harshraj22 — APPROVED** [review]
### aap devil ke piche devil aap ke piche

**Comment by abhiisshheekk** [comment]
> ### aap devil ke piche devil aap ke piche

Too much fun 🤣

**Review by rishitsaiya — APPROVED** [review]
Meri ek taang nakli hai!

**Comment by iam41** [comment]
this change is awesome.

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
