### PR TITLE
edit dart

### PR DESCRIPTION
**Pull request by iam41**
I have corrected the previous edit to uninstall dart.

### CODE REVIEW

**Review by abhiisshheekk — APPROVED** [review]
“I’ll take a potato chip AND EAT IT!” - Light Yagami 🥇

**Review by Manjeetkapil — APPROVED** [review]
Most beautiful thing i have ever seen

**Review by Shiru99 — APPROVED** [review]
You can't just skip ahead to where you think your life should be.

**Comment by Shiru99** [comment]
> “I’ll take a potato chip AND EAT IT!” - Light Yagami

lets try kurkure

**Comment by Shiru99** [comment]
> Most beautiful thing i have ever seen

isi liye bol raha tha Goa chalte he

**Review by rishitsaiya — APPROVED** [review]
Mujhe college waapis jana hai 😢

**Pull request merged**
