### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by abhiisshheekk**

### CODE REVIEW

**Review by harshraj22 — APPROVED** [review]
This is unbelivable ! Another Masterpiece ! Even aliens will remember you for this contribution of yours till eternity !

**Review by Shiru99 — APPROVED** [review]
very very very useful for beginners

**Review by rishitsaiya — APPROVED** [review]
With this you are eligible to become : Slapbet Commissioner

**Review by Manjeetkapil — APPROVED** [review]
This is purely a masterpiece! This post changed my mind

**Review by iam41 — COMMENTED** [review]
wooooooooooooow, nicely done.

**Pull request merged**
