### PR TITLE
added hello world in ruby

### PR DESCRIPTION
**Pull request by abhiisshheekk**

### CODE REVIEW

**Review by harshraj22 — APPROVED** [review]
Wow ! This was the missing piece of our great repo ! This would help us to cross the galaxies and travel through time ! Great job ! Now we can save poor Harsh from getting DX in NSO ! :100: :tada:

**Review by Shiru99 — APPROVED** [review]
very useful for beginners! 
Informative !!

but copied from me : (     1st_place_medal

**Review by rishitsaiya — APPROVED** [review]
Wow

**Review by Manjeetkapil — APPROVED** [review]
Rasode m kaun tha ? Ruby!

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
