### PR TITLE
instructions to run ruby program

### PR DESCRIPTION
**Pull request by abhiisshheekk**

### CODE REVIEW

**Review by harshraj22 — APPROVED** [review]
Wow ! So amazingly written ! Even computer can read this and follow on its own ! Great work !

**Review by Shiru99 — APPROVED** [review]
very useful for beginners! 
Informative !!

Again, :1st_place_medal:

**Review by rishitsaiya — APPROVED** [review]
Machine Learning :100: :rofl:

**Review by Manjeetkapil — APPROVED** [review]
Amazing

**Review by iam41 — COMMENTED** [review]
nicely done.

**Pull request merged**
