### PR TITLE
Leap Year Detector

### PR DESCRIPTION
**Pull request by Pasindu-Vishmika**
@rishitsaiya please labeld as **Hacktober- accepted** .Thank you.

### CODE REVIEW

**Comment by rishitsaiya** [comment]
Please put this file in `Problems Codes` directory.

**Comment by Pasindu-Vishmika** [comment]
can you close this and i'll create new full request.because i'm new to github

**Comment by rishitsaiya** [comment]
No worries, I changed it. 

@Pasindu-Vishmika From next time, be alert on where u are adding file. It should be appropriate enough to be put there.

**Comment by Pasindu-Vishmika** [comment]
Thanks @rishitsaiya for your advices,Im very happy about it.Again Thank You Very Much

**Pull request merged**
